<?php

use Illuminate\Database\Seeder;

class AboutSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create();

        \App\Models\About::create([
            'president_message' => '<p align="justify">Dear Sir / Madam,</p><br><p align="justify">Greetings and welcome to our company, <b>PT. SALWA ANUGERAH SEMESTA (SALWA ENGINEERING)</b>. We are proud of the many great projects we have built. We have extensive expertise and an impressive resume of work in multi-disciplinary design, engineering, procurement, construction, and project management services.</p><br><p align="justify">The history of excellence began in 2004 when <b>SALWA ENGINEERING</b> was established to involve itself in the national economic development, especially in the industrial field.</p><br><p align="justify">Today, our company has emerged as one of the leading companies in Engineering, Procurement, and Construction (EPC) of industrial and mining plants, Oil and Gas plants, power generations, infrastructures and many more related fields to contribute to the communities where we live and work. The long lists of our clients are the proof of our high achievements in fulfilling our commitments.</p><br><p align="justify">Experienced, dynamic, and open-minded leaders, together with the quality and commitment of our workers ensure that our company will continue its success story in the future and stay one step ahead of similar companies.</p><br><p align="justify"><b>SALWA ENGINEERING</b> portrays key competencies and resources imperative for strategic business success. With our well-qualified and highly motivated leaders and workers as our support, we will be more than ready to focus on you soon – as our future clients and customers – and commit to give our best services to you. Please enjoy your trip around the world of <b>SALWA ENGINEERING</b>. We look forward to an opportunity to serve your needs in the near future.</p>',
            'company_history' => '<p align="justify"><b>PT. SALWA ANUGERAH SEMESTA (SALWA ENGINEERING)</b> established in 2002 in Surabaya – East Java – Indonesia, and is engaged in general contracting and trading. In the same year won the trust of Surabaya City Government Department of Water Resources for flood control projects in the city of Surabaya - East Java.</p><br><p align="justify">In addition to environmental work in Surabaya City Government, <b>SALWA ENGINEERING</b> also trusted to handle some private manufacture, plant projects, and telecommunication towers in the year 2005 - 2008.</p><br><p align="justify">In the year 2008, <b>SALWA ENGINEERING</b> got a larger confidence to develop themselves in the field of EPC (Engineering, Procurement & Construction), characterized by the Mini Oil Refinery project at <b>EXXON MOBILE</b> block Bojonegoro – East Java – Indonesia. The project is a milestone for <b>SALWA ENGINEERING</b>, because in this project all abilities have been tested and made <b>SALWA ENGINEERING</b> excited to continue to grow.</p><br><p align="justify">In 2010, due to business growth of <b>SALWA ENGINEERING</b>, then <b>SALWA GROUP</b> as the holding to make a break through with a separate EPC division and other divisions. From then until now <b>SALWA ENGINEERING</b> engaged in the EPC with customer is a major Oil and Gas.</p><br><p align="justify"><b>SALWA ENGINEERING</b> continues to develop the ability to participate actively as part of the development of this beloved country, in INDONESIA particularly and overseas generally.</p>',
            'vision' => '<p align="justify">WE STRIVE TO SERVE THE MOST REASONABLE <b>COST</b>, THE BEST <b>QUALITY</b> IN PRODUCT AND SERVICES, AND ON TIME <b>DELIVERY</b> COMMITTED TO OUR CUSTOMER SATISFACTION.</p>',
            'mission' => '<ol><li>TO ENSURE THE SUSTAINABLE GROWTH BY DEVELOPING OUR MANPOWER AND QUALITY TO ACCURATELY MEET THE NEEDS OF OUR CLIENTS.</li><li>TO PROVIDE PROFESSIONAL SERVICES AND HIGH QUALITY PRODUCTS  AND SERVICES.</li><li>TO DEVELOP STRONG AND PROFOUND PARTNERSHIP WITH OUR CLIENTS AND CUSTOMERS AS WELL AS OUR SUPPLIERS.</li><li>TO PROVIDE A SAFE WORK ENVIRONMENT AND MINI MIZE ENVIRONMENTAL IMPACT.</li></ol>',
            'engineering' => '<p>As an engineering company, <b>SALWA ENGINEERING</b> offers the highly experienced and skillful lead team to produce every detail concepts and engineering quality plants with consideration to priority of economically and time efficiency as our best efforts to create the best end-product to optimum condition for our clients. By such enhancement of skill, <b>SALWA ENGINEERING</b> is capable to offer our clients the most qualified engineering services well-known worldwide in many project engineering areas, such as :</p><ol><li>Project Management Consulting</li><li>Conceptual Project Planning and Development</li><li>Front-to-End Engineering Design (FEED)</li><li>Preliminary Design</li><li>Detail Design Engineering</li><li>Feasibility Studies</li></ol>',
            'procurement' => '<p><b>SALWA ENGINEERING</b> procures materials with an eye toward economic rationality and the environmental load that includes quality costs, delivery lead times, reliability, services, etc. As a result, we continue to use the best raw materials, supplemental materials, equipment and parts, and services, whether inside the country or around the world. We are committed to create strong and wide-ranged partnerships with our business partners, and are continuously looking for aggressive proposals. We continually drive improvement of performance as an in-house and third party (outsourced) service to our diverse client portfolio. Our professional procurement team supports the projects with Basic Procurement Planning, Inquiries, Quotations Analysis, Vendor Selection, Workshop Fabrication, Quality Inspection, Customs Clearanceand Import/Export Formalities.</p><u><b>The goal of procurement sectors are :</b></u><ol><li>To be considered as a procurement and project management leader by our clients in our respective markets.</li><li>Committed to Quality Control System, all of equipment and materials undergo through inspection and witness ingactivities, corrective actions for non-performance, and completion of quality records to comply with ISO 9001:2000 standards.</li></ol>',
            'construction' => '<p><b>SALWA ENGINEERING</b> is known as accompany with good reputation of professional engineers with experience and reputable achievements. Our expertise spans a wide range from pre-construction services to complete turn-key construction projects. Integrity, quality and innovation are the characteristics that distinguish <b>SALWA ENGINEERING</b> as a leading construction company. <b>SALWA ENGINEERING</b> a higher level of service than is found with any other company in the construction industry.</p><p>In the process of building excellence since the first establishment, we have accumulated an impressive list of satisfied clients over the years.</p><p>ENGINEERING also has to deliver value through innovation. We benchmark our best practices in project and construction management, pay attention to lessons learned and constantly challenge ourselves to do better. From materials and construction methods to management techniques and information systems, we always seek new and better ways to help our customers achieve their goals.</p><p>Our successful construction approach is based on construction management system i.e. an aggressive subcontractor administration, on time construction schedule, accurate cost control, and low overhead. <b>SALWA ENGINEERING</b> employs only qualified subcontractors who share our goal in creating a quality cost-competitive project.</p>',
        ]);
    }
}
